const regionesComunas = {
    "Región de Arica y Parinacota": [
        "Arica",
        "Camarones",
        "Putre",
        "General Lagos"
    ],
    "Región de Tarapacá": [
        "Iquique",
        "Alto Hospicio",
        "Pica",
        "Pozo Almonte",
        "Camiña",
        "Colchane",
        "Huara"
    ],
    "Región de Antofagasta": [
        "Antofagasta",
        "Mejillones",
        "Tocopilla",
        "Calama",
        "San Pedro de Atacama",
        "Sierra Gorda",
        "Antofagasta"
    ],
    "Región de Atacama": [
        "Copiapó",
        "Caldera",
        "Tierra Amarilla",
        "Chañaral",
        "Diego de Almagro",
        "Vallenar",
        "Huasco"
    ],
    "Región de Coquimbo": [
        "La Serena",
        "Coquimbo",
        "Andacollo",
        "La Higuera",
        "Paiguano",
        "Vicuña",
        "Ovalle",
        "Combarbalá",
        "Monte Patria",
        "Punitaqui",
        "Río Hurtado"
    ],
    "Región de Valparaíso": [
        "Valparaíso",
        "Viña del Mar",
        "Concón",
        "Quintero",
        "Puchuncaví",
        "Casablanca",
        "San Antonio",
        "El Quisco",
        "El Tabo",
        "Santo Domingo",
        "Cartagena",
        "Los Andes",
        "San Esteban",
        "Llay Llay",
        "Rinconada",
        "San Felipe",
        "Putaendo",
        "Santa María",
        "Catemu",
        "Panquehue",
        "Llaillay"
    ],
    "Región Metropolitana": [
        "Santiago",
        "Cerro Navia",
        "Estación Central",
        "Independencia",
        "La Florida",
        "Las Condes",
        "Lo Barnechea",
        "Macul",
        "Maipú",
        "Ñuñoa",
        "Pedro Aguirre Cerda",
        "Peñalolén",
        "Providencia",
        "Pudahuel",
        "Quilicura",
        "Quinta Normal",
        "Recoleta",
        "Renca",
        "San Bernardo",
        "San Joaquín",
        "San Miguel",
        "Vitacura"
    ],
    "Región del Libertador General Bernardo O'Higgins": [
        "Rancagua",
        "Codegua",
        "Graneros",
        "Machalí",
        "Olivar",
        "Pichidegua",
        "Quinta de Tilcoco",
        "Rengo",
        "Requínoa",
        "San Vicente de Tagua Tagua",
        "Pangipulli"
    ],
    "Región del Maule": [
        "Talca",
        "Cauquenes",
        "Colbún",
        "Linares",
        "Longaví",
        "Maule",
        "Pelarco",
        "Pencahue",
        "Río Claro",
        "San Clemente",
        "San Javier",
        "Villa Alegre",
        "Yerbas Buenas"
    ],
    "Región de Ñuble": [
        "Chillán",
        "Chillán Viejo",
        "El Carmen",
        "Ninhue",
        "Pemuco",
        "Quillón",
        "San Ignacio",
        "Yungay"
    ],
    "Región del Biobío": [
        "Concepción",
        "Coronel",
        "Chiguayante",
        "Hualpén",
        "San Pedro de la Paz",
        "Talcahuano",
        "Penco",
        "Lota",
        "Tomé",
        "Hualqui",
        "Florida",
        "San Rosendo",
        "Santa Juana",
        "Tucapel",
        "Mulchén",
        "Los Ángeles",
        "Antuco",
        "Cabrero",
        "Laja",
        "Nacimiento",
        "Negrete",
        "Quilleco",
        "San Rosendo",
        "Santa Bárbara",
        "Yumbel"
    ],
    "Región de La Araucanía": [
        "Temuco",
        "Carahue",
        "Cunco",
        "Freire",
        "Galvarino",
        "Gorbea",
        "Lautaro",
        "Loncoche",
        "Melipeuco",
        "Nueva Imperial",
        "Pitrufquén",
        "Pucón",
        "San José de la Mariquina",
        "Teodoro Schmidt",
        "Villarrica",
        "Vilcún",
        "Cholchol"
    ],
    "Región de Los Ríos": [
        "Valdivia",
        "Corral",
        "Lanco",
        "Los Lagos",
        "Máfil",
        "Mariquina",
        "Paillaco",
        "Panguipulli"
    ],
    "Región de Los Lagos": [
        "Puerto Montt",
        "Calbuco",
        "Cochamó",
        "Fresia",
        "Frutillar",
        "Los Muermos",
        "Puerto Varas",
        "Castro",
        "Ancud",
        "Chonchi",
        "Dalcahue",
        "Puqueldón",
        "Queilén",
        "Quinchao",
        "Curaco de Vélez",
        "Hualaihué",
        "Palena",
        "Chaitén",
        "Futrono",
        "La Unión",
        "Río Bueno"
    ],
    "Región de Aysén del General Carlos Ibáñez del Campo": [
        "Coyhaique",
        "Aysén",
        "Chile Chico",
        "Cisnes",
        "Guaitecas",
        "Lago Verde",
        "Rio Ibáñez",
        "Tortel"
    ],
    "Región de Magallanes y de la Antártica Chilena": [
        "Punta Arenas",
        "Puerto Natales",
        "Cabo de Hornos",
        "Laguna Blanca",
        "Natales",
        "Porvenir",
        "Primavera",
        "Timaukel"
    ]
};

// Exportar el objeto para su uso en otros módulos
export default regionesComunas;